"""Added initial tables

Revision ID: 570cf625e26c
Revises: 87234782c1bc
Create Date: 2022-12-25 11:43:17.075571

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "570cf625e26c"
down_revision = "87234782c1bc"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "promo_code_status_logs",
        sa.Column("code", sa.String(length=24), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("operation", postgresql.ENUM("reserve", "apply", "free", name="operation"), nullable=False),
        sa.Column("id", sa.UUID(), server_default=sa.text("public.uuid_generate_v4()"), nullable=False),
        sa.Column(
            "created_at", sa.DateTime(timezone=True), server_default=sa.text("CURRENT_TIMESTAMP"), nullable=False
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "promo_codes",
        sa.Column("code", sa.String(length=24), nullable=False),
        sa.Column("expired_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("users_ids", sa.ARRAY(sa.Integer()), server_default=sa.text("ARRAY[]::integer[]"), nullable=False),
        sa.Column("discount_percents", sa.SmallInteger(), nullable=False),
        sa.Column("id", sa.UUID(), server_default=sa.text("public.uuid_generate_v4()"), nullable=False),
        sa.Column(
            "created_at", sa.DateTime(timezone=True), server_default=sa.text("CURRENT_TIMESTAMP"), nullable=False
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_promo_codes_code"), "promo_codes", ["code"], unique=False)
    op.create_table(
        "user_discounts",
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("discount_percents", sa.SmallInteger(), nullable=False),
        sa.Column("expired_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("id", sa.UUID(), server_default=sa.text("public.uuid_generate_v4()"), nullable=False),
        sa.Column(
            "created_at", sa.DateTime(timezone=True), server_default=sa.text("CURRENT_TIMESTAMP"), nullable=False
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_user_discounts_user_id"), "user_discounts", ["user_id"], unique=True)
    op.create_table(
        "promo_codes_statuses",
        sa.Column("code_id", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("status", postgresql.ENUM("reserved", "applied", name="status"), nullable=False),
        sa.Column("id", sa.UUID(), server_default=sa.text("public.uuid_generate_v4()"), nullable=False),
        sa.Column(
            "created_at", sa.DateTime(timezone=True), server_default=sa.text("CURRENT_TIMESTAMP"), nullable=False
        ),
        sa.ForeignKeyConstraint(
            ["code_id"],
            ["promo_codes.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("promo_codes_statuses")
    op.drop_index(op.f("ix_user_discounts_user_id"), table_name="user_discounts")
    op.drop_table("user_discounts")
    op.drop_index(op.f("ix_promo_codes_code"), table_name="promo_codes")
    op.drop_table("promo_codes")
    op.drop_table("promo_code_status_logs")
    # ### end Alembic commands ###
